# -*- coding: utf-8 -*-
"""SVM-Model_Manarth-Patel_Lab2_AIDI-2004_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14reqjRPgDxFwKcfyvmEWeaBO2HDSE5MK
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Load dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data"
columns = ['ID', 'Diagnosis'] + [f'feature_{i}' for i in range(1, 31)]
data = pd.read_csv(url, names=columns)

# Display first few rows
data.head()

# Preprocessing
X = data.drop(columns=['ID', 'Diagnosis'])
y = data['Diagnosis'].map({'M': 1, 'B': 0})

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Training the model
model = SVC(kernel='linear')
model.fit(X_train_scaled, y_train)

# Evaluate the model
y_pred = model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')